### ISSUE TITLE
function batchFH picks GUID as main instead of file name

### ISSUE THREAD

**Issue by Ab-soni** [plantarum/flowPloidy#5]
Hi! I'm having trouble getting the main label of the histogram. It is a long GUID but not the file name. Any suggestions if I can add an argument in batchFlowHist ( ) .  full.names =TRUE, alter.names=FALSE didn't work. 
With thanks
Abhi

**Comment by plantarum** [comment]
Hi Abhi,

Can you send me one of the data files that is giving you this problem?

Thanks,

Tyler

**Comment by Ab-soni** [comment]
[Template.zip.zip](https://github.com/plantarum/flowPloidy/files/10997429/Template.zip.zip)

Hi Tyler, here are the FCS files from different flowmeters with the similar issue. 
Thanks in advance for your help. 
Regards
Abhi

**Comment by plantarum** [comment]
Thanks. 

For individual plots, you can use the `main` to set your own title.

e.g.,

```{R example1}
library(flowPloidy)
viewFlowChannels("11112022_SBMS_Radish_mgSo4_001.fcs")
radish <- FlowHist("11112022_SBMS_Radish_mgSo4_001.fcs",
                   channel = "B_695.40.H")

plot(radish, main = "Radish")
```

![Rplot001](https://user-images.githubusercontent.com/5727138/225928093-7f48375d-9b27-448a-962e-ee6290b02487.jpeg)

That won't help you with Shiny app, which doesn't provide this option. A better fix requires changing the code.

For our flow cytometer, the short file name (basename) is stored in the GUID, and the full name (including the entire path) is stored in the FILENAME. In your case, FILENAME stores the basename. So I think the best solution is to update flowPloidy to use FILENAME instead, after trimming the filename to use just the basename.

I'll test this to make sure it doesn't break anything. In the meantime, try running the following code at the beginning of your analysis:

```R fix
fhFileFix <- function (fh) {
  base::basename(fh@raw@description$FILENAME)
}
assignInNamespace("fhFile", fhFileFix, "flowPloidy")
```

**Comment by plantarum** [comment]
Actually, I've updated the code in the dev branch, so you can install that to test this out if you like. To install:

```R
## Install Bioconductor tools first:
if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
BiocManager::install()

## Install flowCore from Bioconductor:
BiocManager::install("flowCore")

## Install devtools so you can directly access GitHub
install.packages(devtools)
library(devtools)

## Install flowPloidy:
install_github("plantarum/flowPloidy", dependencies = TRUE, 
    build_vignettes = TRUE)
```

**Comment by Ab-soni** [comment]
Thanks, Tyler! It works fine now.
